### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by RadSalty** [Predeactor/discapty#2] opened 2022-02-23 14:46 UTC
Error when using the package in python 3.10, found a simple solution

`Traceback (most recent call last):
  File "test.py", line 5, in <module>
    captcha.generate_captcha()
  File "~\AppData\Local\Programs\Python\Python310\lib\site-packages\discapty\discapty.py", line 153, in generate_captcha
    image: Image = self.captcha.generate(self.code, **self._settings)
  File "~\AppData\Local\Programs\Python\Python310\lib\site-packages\discapty\generator.py", line 262, in generate
    im = self.create_captcha_image(
  File "~\AppData\Local\Programs\Python\Python310\lib\site-packages\discapty\generator.py", line 215, in create_captcha_image
    mask = im.convert("L").point(table)
  File "~\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\Image.py", line 1651, in point
    return self._new(self.im.point(lut, mode))
TypeError: 'float' object cannot be interpreted as an integer`

**Comment by madebylydia** [comment] 2022-02-28 16:21
I was unable to reproduce this issue, however I will assume that #3 fixed this issue. Closing.

**Closed as completed by madebylydia** 2022-02-28 16:21 UTC
